### ISSUE TITLE
24- Intégration des tests dans le pipeline CI/CD

### ISSUE THREAD

**Issue by Alb06** [Alb06/RecruitmentSite#26]
Imported from GitLab:

### Intégration des tests dans le pipeline CI/CD

**Scope** : DevOps (GitLab CI/CD)

**Description fonctionnelle** :\
Automatiser l'exécution des tests dans le pipeline CI/CD pour garantir la qualité du code à chaque commit et pull request.

**Description technique** :

* Configurer le pipeline GitLab CI/CD pour exécuter tous les types de tests
* Mettre en place des rapports de couverture de code
* Configurer les conditions de passage/échec basées sur les résultats des tests
* Exemple de configuration GitLab CI/CD :

```yaml
stages:
  - build
  - test
  - deploy

variables:
  TEST_RESULTS_PATH: "./TestResults"

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - "*/bin/Release/*/"

unit-tests:
  stage: test
  dependencies:
    - build
  script:
    - dotnet test Recrut.Tests/Recrut.Tests.csproj --configuration Release --logger "junit;LogFilePath=$TEST_RESULTS_PATH/unit-test-results.xml" --collect:"XPlat Code Coverage" --results-directory $TEST_RESULTS_PATH
  artifacts:
    paths:
      - $TEST_RESULTS_PATH
    reports:
      junit: $TEST_RESULTS_PATH/unit-test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: $TEST_RESULTS_PATH/*/coverage.cobertura.xml

integration-tests:
  stage: test
  dependencies:
    - build
  services:
    - name: postgres:latest
      alias: postgres-test
  variables:
    POSTGRES_DB: recrutdb_test
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    ConnectionStrings__DefaultConnection: "Host=postgres-test;Port=5432;Database=recrutdb_test;Username=test_user;Password=test_password"
  script:
    - dotnet test Recrut.Tests/Recrut.Tests.csproj --filter Category=Integration --configuration Release --logger "junit;LogFilePath=$TEST_RESULTS_PATH/integration-test-results.xml"
  artifacts:
    paths:
      - $TEST_RESULTS_PATH
    reports:
      junit: $TEST_RESULTS_PATH/integration-test-results.xml

frontend-tests:
  stage: test
  image: node:20
  script:
    - cd Recrut.AppliWeb/recrut.appliweb.client
    - npm ci
    - npm run test -- --no-watch --browsers=ChromeHeadless --code-coverage
  artifacts:
    paths:
      - Recrut.AppliWeb/recrut.appliweb.client/coverage
    reports:
      coverage_report:
        coverage_format: cobertura
        path: Recrut.AppliWeb/recrut.appliweb.client/coverage/cobertura-coverage.xml

e2e-tests:
  stage: test
  image: cypress/browsers:node-20.11.0-chrome-123.0.6312.58-1-ff-123.0
  services:
    - name: postgres:latest
      alias: postgres-test
  variables:
    POSTGRES_DB: recrutdb_test
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
  script:
    - cd Recrut.AppliWeb/recrut.appliweb.client
    - npm ci
    - npm run build
    - cd ../..
    - dotnet run --project Recrut.API/Recrut.API.csproj --configuration Release --urls http://localhost:5000 &
    - cd Recrut.AppliWeb/recrut.appliweb.client
    - npx cypress run
  artifacts:
    paths:
      - Recrut.AppliWeb/recrut.appliweb.client/cypress/videos
      - Recrut.AppliWeb/recrut.appliweb.client/cypress/screenshots
    when: always
```

**Critères d'acceptation** :

* **Fonctionnels** : Pipeline CI/CD exécutant tous les tests automatiquement et générant des rapports
* **Techniques** : Configuration correcte des environnements de test, gestion appropriée des rapports et de la couverture de code

**Criticité** : Haute – L'automatisation des tests est essentielle pour maintenir la qualité du code

**Labels recommandés** : DevOps, CI/CD, GitLab, Test Automation

**Estimation du temps nécessaire** : 8 heures

**Liens utiles** :

* https://docs.gitlab.com/ee/ci/testing/
