### ISSUE TITLE
29- Modifier la CI/CD pour synchroniser toute branche GitLab vers la branche main GitHub

### ISSUE THREAD

**Issue by Alb06** [Alb06/RecruitmentSite#35]
Imported from GitLab:

# Modifier la CI/CD pour synchroniser toute branche GitLab vers la branche main GitHub

## Description fonctionnelle :
Améliorer le processus de synchronisation entre GitLab et GitHub pour permettre aux développeurs de visualiser leur travail en cours sur la branche main de GitHub, quelle que soit la branche de travail sur GitLab. Ce comportement facilitera le partage de code et les revues avant la fusion définitive sur main.

## Description technique :
Modifier le pipeline CI/CD GitLab existant pour ajouter un nouveau job qui s'exécutera à chaque push sur n'importe quelle branche. Ce job devra :

1. Se déclencher pour tout push sur n'importe quelle branche de GitLab
2. Pousser le contenu de la branche courante vers la branche `main` de GitHub 
3. Respecter les contraintes de sécurité (SSH keys)
4. Ne pas interférer avec le job existant `mirror_to_github` qui s'occupe de la synchronisation lors des merges sur main

Exemple de code à ajouter dans le fichier `.gitlab-ci.yml` :

```yaml
push_current_to_github_main:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add github git@github.com:Alb06/RecruitmentSite.git || true
    - git fetch github
    - git push github HEAD:main -f
  rules:
    - if: $CI_COMMIT_BRANCH != 'main'
      when: always
    - when: never
```

### Fonctionnels :
- À chaque push sur une branche GitLab (autre que main), cette branche doit être synchronisée vers la branche main de GitHub
- Le pipeline ne doit pas échouer si les opérations de synchronisation rencontrent des problèmes mineurs
- Lors d'un merge sur main dans GitLab, le comportement existant doit être conservé (miroir complet vers GitHub)

### Techniques :
- Le code poussé vers GitHub doit être exactement le même que celui présent dans la branche GitLab source
- Les permissions SSH doivent être correctement configurées
- Le pipeline doit s'exécuter rapidement (< 2 minutes pour cette tâche)

## Criticité : Moyenne
Justification : Bien que cette fonctionnalité améliore significativement le workflow de développement et facilite les revues de code, elle n'affecte pas directement la production ou la sécurité du système.

## Labels recommandés : 
CI/CD, GitLab, GitHub, DevOps

## Estimation du temps nécessaire : 
3 heures (incluant les tests et ajustements)

## Conseils supplémentaires :
- Tester la configuration avec une branche temporaire avant de la déployer définitivement
- Vérifier que les clés SSH utilisées ont les permissions appropriées sur le dépôt GitHub
- S'assurer que la force push (`-f`) utilisée est bien intentionnelle car elle écrasera l'historique de la branche main sur GitHub

## Liens utiles :
- Configuration CI/CD actuelle : `.gitlab-ci.yml`
- Documentation GitLab CI/CD : https://docs.gitlab.com/ee/ci/
